blueprint:
  name: Remote - Müller Lint Tint - Z2M MQTT v1
  description: Control lights with a Müller-Lint Tint Switch.
  domain: automation
  input:
    remote:
      name: Remote mqtt topic
      description: This must be the TOPIC from zigbee2mqtt. For example z2m/remote_1
      selector:
        text:
    light:
      name: Target light
      selector:
        entity:
          domain: light
    step:
      name: Dimming step in percent
      default: 10
      selector:
        number:
          min: 0.0
          max: 50.0
          mode: slider
          step: 1.0
          unit_of_measurement: "%"
    transition:
      name: transition duration
      default: 1
      selector:
        number:
          min: 0.0
          max: 5.0
          mode: slider
          step: 0.5
          unit_of_measurement: "s"
    scene_1:
      name: Sunset Scene
      default: {}
      selector:
        entity:
          domain: scene
    scene_2:
      name: Reading Scene
      default: {}
      selector:
        entity:
          domain: scene
    scene_3:
      name: Party Scene
      default: {}
      selector:
        entity:
          domain: scene
    scene_4:
      name: Relax Scene
      default: {}
      selector:
        entity:
          domain: scene
    scene_5:
      name: Night Scene
      default: {}
      selector:
        entity:
          domain: scene
    scene_6:
      name: Love Scene
      default: {}
      selector:
        entity:
          domain: scene

trigger:
  - platform: mqtt
    topic: !input "remote"
action:
  - variables:
      command: "{{trigger.payload_json.action}}"
      step: !input "step"
      negative_step: "{{ -1 * (step | int) }}"
  - choose:
      - conditions: "{{ command == 'on' or command == 'off' }}"
        sequence:
          - service: light.toggle
            data_template:
              entity_id: !input "light"
              transition: !input "transition"
      - conditions: "{{ command == 'brightness_step_down' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: !input "light"
              brightness_step_pct: "{{ negative_step }}"
              transition: !input "transition"
      - conditions: "{{ command == 'brightness_step_up' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: !input "light"
              brightness_step_pct: "{{ step }}"
              transition: !input "transition"

      - conditions: "{{ command == 'color_temperature_move' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: !input "light"
              color_temp: "{{trigger.payload_json.action_color_temperature}}"
              transition: !input "transition"

      - conditions: "{{ command == 'color_move' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: !input "light"
              xy_color:
                - "{{trigger.payload_json.action_color.x}}"
                - "{{trigger.payload_json.action_color.y}}"
              transition: !input "transition"

      - conditions: "{{ command == 'scene_1' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_1"

      - conditions: "{{ command == 'scene_2' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_2"

      - conditions: "{{ command == 'scene_3' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_3"

      - conditions: "{{ command == 'scene_4' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_4"

      - conditions: "{{ command == 'scene_5' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_5"

      - conditions: "{{ command == 'scene_6' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input "scene_6"
