blueprint:
  name: Light - Sync 2 lights States v2
  description: Bind two lights together to act in unison 
# original_url: 
  domain: automation
  input:
    light_1:
      name: light (shelly)
      selector:
        entity:
          domain: light
    light_2:
      name: light (hue)
      selector:
        entity:
          domain: light

variables:
  light_1: !input light_1
  light_2: !input light_2

trigger:
  - platform: state
    entity_id: 
      - !input light_1
      - !input light_2

mode: single

condition:
  '{{ trigger.to_state.state != trigger.from_state.state }}'

action:
  # Set to target value
  - choose:
    - conditions:
      - '{{ trigger.entity_id != light_1 }}'
      - '{{ trigger.to_state.state != states(light_1) }}'
      sequence:
        - service: 'light.turn_{{ trigger.to_state.state }}'
          entity_id: !input light_1

  - choose:
    - conditions:
      - '{{ trigger.entity_id != light_2 }}'
      - '{{ trigger.to_state.state != states(light_2) }}'
      sequence:
        - service: 'light.turn_{{ trigger.to_state.state }}'
          entity_id: !input light_2
