blueprint:
  name: Light - Automatic On Off
  description: Turn on Off when other based on other state.
  domain: automation
  source_url: https://github.com/revin34/HA-Blueprints/blob/main/blueprints/light_auto_on_off.yaml
  input:
    light_source:
      name: Light
      selector:
        target:
          entity:
            domain: light     
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

mode: single
max_exceeded: silent

trigger:
  platform: state
  id: light_on
  entity_id: !input light_source
  from: "off"
  to: "on"

trigger:
  platform: state
  id: light_off
  entity_id: !input light_source
  from: "on"
  to: "off"

action:
- choose:
  - conditions:
    - condition: trigger
      id: light_on
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_target    
  - conditions:
    - condition: trigger
      id: light_off
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_target  
